# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iWeather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iWeather
  pod 'Alamofire'
  target 'iWeatherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iWeatherUITests' do
    # Pods for testing
  end

end
